### ISSUE TITLE
Multi-domain app support question

### ISSUE THREAD

**Issue by richardvenneman** [pixielabs/letsencrypt-rails-heroku#1]
Thanks for the great gem, just pushed it into production and it works perfect.

For another multilingual app, we have to support multiple domains. Not just different subdomains but different TLD's, e.g.:

www.website.com
www.website.nl
www.website.de

How would you support such setup? Thanks in advance!

**Comment by jalada** [comment]
Thanks for the praise, exciting to hear it's being used and worked for you ☺️👍

The ACME_DOMAIN config variable takes a comma separated list of domains. You should be able to supply all your domains in that variable and the gem will request a multi-domain certificate for them all.

That said, I can't remember checking if it works properly. So let me know if you have a problem. I'll also double check when I can.

**Comment by richardvenneman** [comment]
Thanks for the quick reply @jalada! I thought multi domain certificates weren't supported by LE yet, but with regard to your comment I found [this thread](https://community.letsencrypt.org/t/please-support-multi-domain-ssl-certificates-like-the-ones-on-positivessl/867/21), stating that it does, which is good news.

I entered multiple comma-separated domain names as ACME_DOMAIN, but unfortunately the rake tasks aborts on the [authorize directive](https://github.com/pixielabs/letsencrypt-rails-heroku/blob/761f6bebf024634bb6c1156190f178843e3574aa/lib/tasks/letsencrypt.rake#L28):

```
Registering with LetsEncrypt...Done!
rake aborted!
Acme::Client::Error::Malformed: Invalid character in DNS name
/app/vendor/bundle/ruby/2.3.0/gems/acme-client-0.3.7/lib/acme/client/faraday_middleware.rb:41:in `raise_on_error!'
/app/vendor/bundle/ruby/2.3.0/gems/acme-client-0.3.7/lib/acme/client/faraday_middleware.rb:31:in `on_complete'
/app/vendor/bundle/ruby/2.3.0/gems/acme-client-0.3.7/lib/acme/client/faraday_middleware.rb:16:in `block in call'
/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
/app/vendor/bundle/ruby/2.3.0/gems/acme-client-0.3.7/lib/acme/client/faraday_middleware.rb:16:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
/app/vendor/bundle/ruby/2.3.0/gems/acme-client-0.3.7/lib/acme/client.rb:55:in `authorize'
/app/vendor/bundle/ruby/2.3.0/gems/letsencrypt-rails-heroku-0.2.4/lib/tasks/letsencrypt.rake:30:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/appsignal-1.2.0/lib/appsignal/hooks/rake.rb:15:in `execute'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => letsencrypt:renew
```

It seems the acme-client supports only [authorizing single domains](https://github.com/unixcharles/acme-client#authorize-for-domain). Leaping to conclusions here (I haven't been able to grasp all of LE concepts yet), but I think that the following issue confirms that: https://github.com/unixcharles/acme-client/issues/19.

Please let me know if I can help out in any way!

**Comment by jalada** [comment]
Ahh of course.

The solution is fairly simple then, we need to iterate over all domains, performing challenges for each. It'll be slow ('cos your app will spin up and down every time the config vars change) but it will work.

I'll see what I can do.

**Comment by jalada** [comment]
Try with 0.2.5 @richardvenneman :blush:

**Comment by richardvenneman** [comment]
@jalada I just tested 0.2.5 with an app with 10 domains configured. It took a while indeed, but it worked! Happy to have a secured connection now.

Thanks for the help and quick action!
