### ISSUE TITLE
Timeout when registering with LetsEncrypt

### ISSUE THREAD

**Issue by cbetta** [pixielabs/letsencrypt-rails-heroku#13]
I get the following error when running renew for the first time:

```
> heroku run rake letsencrypt:renew
Running rake letsencrypt:renew on ⬢ perksy-web... up, run.7725 (Standard-1X)
Creating account key...Done!
Registering with LetsEncrypt...rake aborted!
Acme::Client::Error::Timeout: Acme::Client::Error::Timeout
```

Any advice would be welcome

**Comment by cbetta** [comment]
Closing. Problem was with LetsEncrypt

**Comment by jalada** [comment]
Thanks for the report @cbetta :) it was good to know what happens when LetsEncrypt has problems.

**Comment by cbetta** [comment]
@jalada no problem. Interestingly their status page wasn't showing anything but a quick twitter search showed I wasn't the only one having issues.
