### ISSUE TITLE
Redirection Forbidden on URI open

### ISSUE THREAD

**Issue by mikewagz** [pixielabs/letsencrypt-rails-heroku#18]
I'm forcing SSL on my site (via [this gem](https://github.com/tobmatth/rack-ssl-enforcer)), which seems to be causing an error when the URL http://myapp.herokuapp.com tries to redirect to https://myapp.herokuapp.com:

```
Setting config vars on Heroku...Done!
Giving config vars time to change...Done!
Testing filename works (to bring up app)...rake aborted!
redirection forbidden: http://myapp.herokuapp.com/.well-known/acme-challenge/sQS_g4zomh07wUpeAwwzW_U7sDo0LrEtRXfKYqtxhYE -> https://myapp.herokuapp.com/.well-known/acme-challenge/sQS_g4zomh07wUpeAwwzW_U7sDo0LrEtRXfKYqtxhYE
```

Is there a way to renew when forcing SSL for the app?

**Comment by jalada** [comment]
Hi @mikewagz! This is covered in the README under 'Installation' :) you may need to do something slightly different when using `rack-ssl-enforcer`, but the approach should be roughly the same. Is there a reason you're not just using `force_ssl=true` in Rails?

**Comment by mikewagz** [comment]
Ah, silly me. I had forgotten to change that after switching to this SSL Enforcer gem.  Thank you!

I'm using the SSL Enforcer gem because of a subfolder that reverse-proxies to a subdomain which hosts a Wordpress blog.  There were some SSL issues I wanted to avoid, so the SSL Enforcer gem allows for forcing non-SSL on certain paths.

For anyone else coming across this, I used this line to get it working:

`config.middleware.insert_before Rack::SslEnforcer, Letsencrypt::Middleware`
