### ISSUE TITLE
fork of platform-api still needed??

### ISSUE THREAD

**Issue by aunderwo** [pixielabs/letsencrypt-rails-heroku#19]
Your docs state that the jalada fork of the platform-api gem should be used "Until the new API calls are generally available". What's the current status?

**Comment by jalada** [comment]
@aunderwo I actually need to take it upstream. They closed [the issue](https://github.com/heroku/platform-api/issues/49) but I don't see the source code being regenerated after that date so I don't think it supports it yet. But I may be mis-understanding how the gem works.

**Comment by johnhobbs254** [comment]
Also interested in this!

**Comment by jalada** [comment]
It's still needed, and maintaining that fork has caused more issues today. Please nudge Heroku via a support ticket and on their GitHub issues!

**Comment by jalada** [comment]
letsencrypt-rails-heroku is now using the officially-published version of platform-api.
