### ISSUE TITLE
There are issues with the site's certificate chain (net::ERR_CERT_COMMON_NAME_INVALID).

### ISSUE THREAD

**Issue by ffiller** [pixielabs/letsencrypt-rails-heroku#20]
Exactly following the instructions outlined, I get the following error in Chrome:

There are issues with the site's certificate chain (net::ERR_CERT_COMMON_NAME_INVALID).

and in Safari: 

This certificate is not valid (host name mismatch)

Any hints would be greatly appreciated!

**Comment by jalada** [comment]
Hey @ffiller. What domain is this for? It sounds like maybe the website domain you are accessing the app via doesn't match the domain you configured the certificate to be created for, hence the error 'host name mismatch'.

**Comment by ffiller** [comment]
Thanks @jalada. `heroku config:get ACME_DOMAIN` returns `xyz.com,www.xyz.com`. The URL where i'm getting those ssl error is `www.xyz.com`.

**Comment by jalada** [comment]
@ffiller If you bypass the security warning, what does Chrome / Safari *say* the certificate common name(s) is/are? e.g:

![screen shot 2016-12-28 at 11 37 50](https://cloud.githubusercontent.com/assets/126989/21521146/1cbfc246-ccf2-11e6-875a-f75fed59fc48.png)

**Comment by ffiller** [comment]
@jalada Indeed, it is `*.herokuapp.com`

**Comment by jalada** [comment]
@ffiller your [DNS settings](https://devcenter.heroku.com/articles/custom-domains) are incorrect and are pointing at the non-SSL Heroku DNS endpoint. Use `heroku domains` to see what your CNAME should be (probably something ending in `herokudns.com`).

**Comment by ffiller** [comment]
@jalada You are correct, sir. Thanks! :)
