### ISSUE TITLE
Big thanks

### ISSUE THREAD

**Issue by chriso0710** [pixielabs/letsencrypt-rails-heroku#22]
I just want to pause and take a minute to say a big thanks to @jalada ! 
You did a great job automating heroku SNI and Letsencrypt certs. It does exactly what I was looking for. Usage could not be simpler and it works perfect with my Sinatra app.

Christian

**Comment by jalada** [comment]
@chriso0710 Thank you so much for your exceptionally kind words 😊 it really means a lot. I'm so glad we helped you with securing your app, good on you! 🌟

**Comment by jalada** [comment]
Also just wanted to add that Sinatra support was thanks to the hard work of @cbetta 🎉

**Comment by cbetta** [comment]
😊
