### ISSUE TITLE
SocketError: getaddrinfo: Name or service not known

### ISSUE THREAD

**Issue by jimmybaker** [pixielabs/letsencrypt-rails-heroku#26]
Trying to set this up for the first time. I think I've followed all the steps correctly. However, when I try to run `letsencrypt:renew` on heroku, I get the following error:

```
Testing filename works (to bring up app)...rake aborted!
SocketError: getaddrinfo: Name or service not known
/app/vendor/bundle/ruby/2.2.0/gems/letsencrypt-rails-heroku-0.3.0/lib/tasks/letsencrypt.rake:55:in `block (3 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.2.0/gems/letsencrypt-rails-heroku-0.3.0/lib/tasks/letsencrypt.rake:32:in `each'
/app/vendor/bundle/ruby/2.2.0/gems/letsencrypt-rails-heroku-0.3.0/lib/tasks/letsencrypt.rake:32:in `block (2 levels) in <top (required)>'
```

**Comment by jimmybaker** [comment]
Ok, I solved this by removing the other domain names that I had attached to the app that were no longer needed.

**Comment by Shoma0128** [comment]
I got same problem...
I would appreciate it if you teach me how you fix it in detail...
(what and how did you change? )

**Comment by jalada** [comment]
@Shoma0128 check over the domains you have configured for your Heroku app (run `heroku domains` on the command line); maybe there is one there that doesn't have the correct DNS set up?

**Comment by Shoma0128** [comment]
@jalada Thank you so much for super quick answering.
Should I compare ACME_DOMAIN with the domains I have configured (which is what you mentioned)?
