### ISSUE TITLE
No errors yet my site is still certless.

### ISSUE THREAD

**Issue by fergyfresh** [pixielabs/letsencrypt-rails-heroku#37]
Name              Common Name(s)                        Expires               Trusted  Type
────────────────  ────────────────────────────────────  ────────────────────  ───────  ────
gallimimus-58466  pickbillyup.com, www.pickbillyup.com  2017-05-22 01:25 UTC  True     SNI

PLEASE HELP. Not sure what to put in the issue since I am so confused. Hopefully its just a time delay thing and it will be better in the AM and I can delete this issue before anyone has to see it.

**Comment by jalada** [comment]
Hi @fergyfresh! Sorry to hear you're having problems.

As per the README, you need to make sure your DNS settings match what Heroku tell you to set them to. When you add SNI-based SSL, you need to update your domain's CNAME from its existing `.herokuapp.com` CNAME to whatever it tell you to do in the output of `heroku domains`.

HTH! Let us know if you still have issues.

**Comment by fergyfresh** [comment]
I still had the residual `.herokuapp.com` CNAME as I wasn't sure if it was needed or not. I deleted it and reran the setup and hopefully that fixes it for me. Thanks for the help!

**Comment by fergyfresh** [comment]
I restarted my heroku server an hour after deleting the extra CNAME from google domains and it works! Thanks for your help in reiterating that part of the README to me. I was a little lost as this was the first time doing this.
