### ISSUE TITLE
Unable to clear redirect from force_ssl

### ISSUE THREAD

**Issue by kbbpartners** [pixielabs/letsencrypt-rails-heroku#40]
Per the README, I've got `config.middleware.insert_before ActionDispatch::SSL, Letsencrypt::Middleware` in config/application.rb. Indeed, running `heroku run rake middleware` shows:

```
...
use Letsencrypt::Middleware
use ActionDispatch::SSL
...
```

But, `heroku run rake letsencrypt:renew` results in:

```
Testing filename works (to bring up app)...rake aborted!
redirection forbidden
```

This is on ruby 2.3.1, Rails 4.2.6.

Have I missed something?

**Comment by jalada** [comment]
Hi @kbbpartners. Maybe something is redirecting ahead of your Heroku app; what's your DNS setup?

**Comment by kbbpartners** [comment]
I have two subdomains on this app: `access.kbb.partners` and `blackbox.kbb.partners`. (Yes, 'partners' is the TLD we use for this staging.) I've included both subdomains in ACME_DOMAIN. On the DNS side, I have CNAMEs for each subdomain pointing to the corresponding Heroku endpoints, which were provided by Heroku's custom domain settings.

The full error thrown by the rake task looks like: 

`redirection forbidden: http://access.kbb.partners/.well-known/acme-challenge/<code> -> https://access.kbb.partners/.well-known/acme-challenge/<code>`

**Comment by kbbpartners** [comment]
I'm going to close this issue, although we were unable to resolve this issue. In the end, here is where we left it:

- The redirection was the result of a mismatch of the `Letsencrypt.configuration.acme_challenge_filename` and the current path at `env['PATH_INFO']`. Since this match was failing, the middleware called `@app.call(env)`, which triggered the redirection downstream.
- We were never able to understand how the middleware should be aware of the current value of the Heroku environment variables `ACME_CHALLENGE_FILENAME` and `ACME_CHALLENGE_FILE_CONTENT`.  The rake task updates the Heroku variables mid-stream, but the `Letsencrypt.configuration` values remained as they were at the time of initialization of the middleware. As a result, they never matched. We weren't able to find a satisfactory way to pass the updated values back to the middleware.

**Comment by jalada** [comment]
I'm unsure why there is a mismatch between your `ACME_CHALLENGE_FILENAME` variable and the request from LetsEncrypt. Could it be that it is a previous value from a previous run of the rake task?

The middleware is aware of the current variables because they've been updated by the Heroku task. Assuming you are updating the environment variables for the correct app (the one responding to web requests), the app will restart when the variables are changed via the API and will have the new values.

Is there something about your Heroku configuration that means this restart doesn't happen in the normal manner?

**Comment by jalada** [comment]
@kbbpartners I've had an idea that may help fix this, and I'm tracking it with issue https://github.com/pixielabs/letsencrypt-rails-heroku/issues/41, I'll try and get a fix out for you to retry.

**Comment by jalada** [comment]
@kbbpartners please can you try v1.1.1.

**Comment by kbbpartners** [comment]
Thanks! I'll have a look ASAP.

**Comment by jalada** [comment]
Hey @kbbpartners, I noticed a bug with my fix. If you haven't already, don't bother trying 1.1.1, and just try v1.1.3 :)

**Comment by kbbpartners** [comment]
No problem—we hit a LetsEncrypt rate limit during our efforts to correct this, so we're in a holding pattern for a few days anyway.

**Comment by kbbpartners** [comment]
OK—I can confirm that this worked. 

However, I noticed one minor issue. We have two Custom Domains and then the standard-issue Heroku Domain. We only need certificates for the Custom Domains, so the third certificate (for the Heroku Domain) is superfluous for us—we never use that subdomain.

I'm guessing this is probably related to https://github.com/pixielabs/letsencrypt-rails-heroku/issues/44

Anyway, thank you!
