### ISSUE TITLE
Persist account keys

### ISSUE THREAD

**Issue by jalada** [pixielabs/letsencrypt-rails-heroku#50]
As discussed in https://github.com/pixielabs/letsencrypt-rails-heroku/issues/47, and in the README, we should really persist account keys in between renewals instead of re-registering with LetsEncrypt every time.

There may be an undocumented account limit per email address, which we might run in to. We've asked: https://community.letsencrypt.org/t/maximum-accounts-per-email-address/29908

**Comment by jalada** [comment]
[Response](https://community.letsencrypt.org/t/maximum-accounts-per-email-address/29908) indicates no limit, but obviously it'd still be nice to do this.

**Comment by davidlibrera** [comment]
@jalada the registration step is an association between a private_key and an email address.
Imho generating a new account private_key and registering that key is a security improvement, so I suggest to continue with this.
It has no cost registering a new private key so, why not?

**Comment by jalada** [comment]
Closed by #62
