### ISSUE TITLE
Not installing heroku-cli-oauth because it is already installed as a core plugin.

### ISSUE THREAD

**Issue by andrewhavens** [pixielabs/letsencrypt-rails-heroku#51]
I am going through the instructions in the readme and it says that the Heroku plugin is already installed, so I'm wondering if this step should be removed from the readme. Not sure if it is installed by default because I have a newer version, or if I previously installed it without realizing it.

```
$ heroku plugins:install heroku-cli-oauth
 ▸    Not installing heroku-cli-oauth because it is already installed as a core plugin.
$ heroku -v
heroku-cli/5.7.0-713be60 (darwin-amd64) go1.7.5
```

**Comment by davidlibrera** [comment]
@andrewhavens yes, I think that is impossible ensure that everyone has che heroku-cli-oauth installed. In the worst case you see the warning you mentioned before. Maybe is better to leave that command in the README

**Comment by jalada** [comment]
@andrewhavens I agree with @davidlibrera. I get the same error:

```console
$ heroku plugins:install heroku-cli-oauth
  Not installing heroku-cli-oauth because it is already installed as a core plugin.
```

I'm going to guess you previously installed it.
