### ISSUE TITLE
Please get modified platform-api into heroku/platform-api

### ISSUE THREAD

**Issue by david-a-wheeler** [pixielabs/letsencrypt-rails-heroku#55]
The current directions require installation of a forked version of platform-api.  I think it'd be much better/safer if that were merged into the upstream heroku/platform-api.

Could you submit a pull request to heroku/platform-api to get the necessary support into that?  Here is a [related issue](https://github.com/heroku/platform-api/issues/63).

**Comment by jalada** [comment]
Hi @david-a-wheeler. Completely agree, I'm not happy with using a fork of the gem.

However there are already multiple issues and PRs open requesting that they update the schema:

 - https://github.com/heroku/platform-api/issues/49
 - https://github.com/heroku/platform-api/pull/56

It's also been discussed within letsencrypt-rails-heroku:

 - https://github.com/pixielabs/letsencrypt-rails-heroku/issues/35
 - https://github.com/pixielabs/letsencrypt-rails-heroku/issues/19

**Comment by jalada** [comment]
Two years to the day! Letsencrypt-rails-heroku is now using the officially-published version of platform-api.
