### ISSUE TITLE
Heroku Private spaces don't support SSL auto renewal

### ISSUE THREAD

**Issue by thomas-riboulet-finalcad** [pixielabs/letsencrypt-rails-heroku#58]
While I was super excited about this I found out that Heroku Private spaces don't support SSL Auto renewal so this gem would still be very useful to a number of people.

read more : https://devcenter.heroku.com/articles/automated-certificate-management#known-limitations

**Comment by jalada** [comment]
Thanks @thomas-riboulet-finalcad, useful to know, I'll update the README.
