### ISSUE TITLE
ACME v2 support

### ISSUE THREAD

**Issue by mashedkeyboard** [pixielabs/letsencrypt-rails-heroku#59]
At the moment, the most significant use case for this gem to my mind is wildcard domain certificates, as Heroku has no native support for them though ACM.

However, at present, the gem uses only the ACME v1 endpoints for Let's Encrypt, and as a consequence doesn't support wildcard domain names.

Can an option be added for ACME v2, or the gem as a whole migrated?

**Comment by jalada** [comment]
Hi @mashedkeyboard, thanks for getting in touch! You're right, wildcard domain certificates is beyond ACM right now.

I'm not familiar with ACME v2, but it sounds like it resolves the issues we had around wildcard domains https://github.com/pixielabs/letsencrypt-rails-heroku/issues/39, so it feels worth investigating. Have you asked Heroku if ACME v2 is on their roadmap?

Thanks for bringing this to our attention 🌟

**Comment by mashedkeyboard** [comment]
Heroku have mentioned that [it's on their roadmap but with no definite date](https://help.heroku.com/EUV5TCYK/why-doesn-t-automated-certificate-management-support-wildcard-domains).

`acme-client` (supports it by default now)[https://github.com/unixcharles/acme-client]. I'm looking into how many breaking changes there are and how easy it would be to upgrade.

**Comment by mashedkeyboard** [comment]
I'm working on this over at https://github.com/mashedkeyboard/letsencrypt-rails-heroku.

The big issue is going to be DNS challenges, which are required for wildcard domains. Implementation of this will inevitably require CloudFlare APIs or similar.

**Comment by jalada** [comment]
Closed by #62
