### ISSUE TITLE
Heroku preboot causes OpenURI::HTTPError: 500 Internal Server Error

### ISSUE THREAD

**Issue by olivierlacan** [pixielabs/letsencrypt-rails-heroku#9]
It seems like the [5 second pause](https://github.com/pixielabs/letsencrypt-rails-heroku/blob/72fe5a008b37c66a896cbb341a1fa9bc1fb0022f/lib/tasks/letsencrypt.rake#L47) is not long enough for the challenge URL to become available with an app that uses [Heroku Preboot](https://devcenter.heroku.com/articles/preboot) when running `heroku run rake letsencrypt:renew`.

It results in the following error, most likely because the new dynos haven't been provisioned yet. It takes anything between 5 and 10 minutes for preboot to boot the new dynos.

```
rake aborted!
OpenURI::HTTPError: 500 Internal Server Error
/app/vendor/bundle/ruby/2.3.0/gems/letsencrypt-rails-heroku-0.2.7/lib/tasks/letsencrypt.rake:55:in `block (3 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/letsencrypt-rails-heroku-0.2.7/lib/tasks/letsencrypt.rake:32:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/letsencrypt-rails-heroku-0.2.7/lib/tasks/letsencrypt.rake:32:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/bugsnag-4.0.0/lib/bugsnag/rake.rb:12:in `execute_with_bugsnag'
Tasks: TOP => letsencrypt:renew
```

I'd suggest mentioning that in the README and recommending that people disable preboot while running the rake task at least: 

```
heroku features:disable -a myapp preboot
```

**Comment by jalada** [comment]
Thanks, also kinda related to https://github.com/pixielabs/letsencrypt-rails-heroku/issues/6

**Comment by jalada** [comment]
The correct fix for this is to loop & attempt to check the challenge URL multiple times before bailing.
